/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type TransferDataStruct = {
  token: PromiseOrValue<string>;
  payload: PromiseOrValue<BytesLike>;
  partition: PromiseOrValue<BytesLike>;
  operator: PromiseOrValue<string>;
  from: PromiseOrValue<string>;
  to: PromiseOrValue<string>;
  value: PromiseOrValue<BigNumberish>;
  tokenId: PromiseOrValue<BigNumberish>;
  data: PromiseOrValue<BytesLike>;
  operatorData: PromiseOrValue<BytesLike>;
};

export type TransferDataStructOutput = [
  string,
  string,
  string,
  string,
  string,
  string,
  BigNumber,
  BigNumber,
  string,
  string
] & {
  token: string;
  payload: string;
  partition: string;
  operator: string;
  from: string;
  to: string;
  value: BigNumber;
  tokenId: BigNumber;
  data: string;
  operatorData: string;
};

export interface BlockExtensionInterface extends utils.Interface {
  functions: {
    "extensionDeployer()": FunctionFragment;
    "externalFunctions()": FunctionFragment;
    "hasRole(address,bytes32)": FunctionFragment;
    "interfaceLabel()": FunctionFragment;
    "isTokenStandardSupported(uint8)": FunctionFragment;
    "packageHash()": FunctionFragment;
    "requiredRoles()": FunctionFragment;
    "version()": FunctionFragment;
    "initialize()": FunctionFragment;
    "isBlocklisted(address)": FunctionFragment;
    "addBlocklisted(address)": FunctionFragment;
    "removeBlocklisted(address)": FunctionFragment;
    "isBlocklistedAdmin(address)": FunctionFragment;
    "addBlocklistedAdmin(address)": FunctionFragment;
    "removeBlocklistedAdmin(address)": FunctionFragment;
    "onTransferExecuted((address,bytes,bytes32,address,address,address,uint256,uint256,bytes,bytes))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "extensionDeployer"
      | "externalFunctions"
      | "hasRole"
      | "interfaceLabel"
      | "isTokenStandardSupported"
      | "packageHash"
      | "requiredRoles"
      | "version"
      | "initialize"
      | "isBlocklisted"
      | "addBlocklisted"
      | "removeBlocklisted"
      | "isBlocklistedAdmin"
      | "addBlocklistedAdmin"
      | "removeBlocklistedAdmin"
      | "onTransferExecuted"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "extensionDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "externalFunctions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "interfaceLabel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenStandardSupported",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "packageHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiredRoles",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBlocklisted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addBlocklisted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeBlocklisted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlocklistedAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addBlocklistedAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeBlocklistedAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "onTransferExecuted",
    values: [TransferDataStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "extensionDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "externalFunctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "interfaceLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenStandardSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "packageHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBlocklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addBlocklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeBlocklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlocklistedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addBlocklistedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeBlocklistedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onTransferExecuted",
    data: BytesLike
  ): Result;

  events: {
    "BlocklistedAdded(address)": EventFragment;
    "BlocklistedAdminAdded(address)": EventFragment;
    "BlocklistedAdminRemoved(address)": EventFragment;
    "BlocklistedRemoved(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "RoleAdded(address,bytes32)": EventFragment;
    "RoleRemoved(address,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BlocklistedAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlocklistedAdminAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlocklistedAdminRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlocklistedRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRemoved"): EventFragment;
}

export interface BlocklistedAddedEventObject {
  account: string;
}
export type BlocklistedAddedEvent = TypedEvent<
  [string],
  BlocklistedAddedEventObject
>;

export type BlocklistedAddedEventFilter =
  TypedEventFilter<BlocklistedAddedEvent>;

export interface BlocklistedAdminAddedEventObject {
  account: string;
}
export type BlocklistedAdminAddedEvent = TypedEvent<
  [string],
  BlocklistedAdminAddedEventObject
>;

export type BlocklistedAdminAddedEventFilter =
  TypedEventFilter<BlocklistedAdminAddedEvent>;

export interface BlocklistedAdminRemovedEventObject {
  account: string;
}
export type BlocklistedAdminRemovedEvent = TypedEvent<
  [string],
  BlocklistedAdminRemovedEventObject
>;

export type BlocklistedAdminRemovedEventFilter =
  TypedEventFilter<BlocklistedAdminRemovedEvent>;

export interface BlocklistedRemovedEventObject {
  account: string;
}
export type BlocklistedRemovedEvent = TypedEvent<
  [string],
  BlocklistedRemovedEventObject
>;

export type BlocklistedRemovedEventFilter =
  TypedEventFilter<BlocklistedRemovedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface RoleAddedEventObject {
  caller: string;
  roleId: string;
}
export type RoleAddedEvent = TypedEvent<[string, string], RoleAddedEventObject>;

export type RoleAddedEventFilter = TypedEventFilter<RoleAddedEvent>;

export interface RoleRemovedEventObject {
  caller: string;
  roleId: string;
}
export type RoleRemovedEvent = TypedEvent<
  [string, string],
  RoleRemovedEventObject
>;

export type RoleRemovedEventFilter = TypedEventFilter<RoleRemovedEvent>;

export interface BlockExtension extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BlockExtensionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     * Gets the extension deployer address
     */
    extensionDeployer(overrides?: CallOverrides): Promise<[string]>;

    /**
     * This function is used by the TokenProxy to determine what function selectors to add to the TokenProxy
     * An array of function signatures registered by the extension
     */
    externalFunctions(overrides?: CallOverrides): Promise<[string[]]>;

    hasRole(
      caller: PromiseOrValue<string>,
      roleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * The ERC1820 interface label the extension will be registered as in the ERC1820 registry
     */
    interfaceLabel(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Checks if token standard is supported by the extension
     * @param standard a valid TokenStandard (enum)
     */
    isTokenStandardSupported(
      standard: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * Gets the package hash (generated using the package name and deployer address)
     */
    packageHash(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Gets the list of required roles required to call the extension
     */
    requiredRoles(overrides?: CallOverrides): Promise<[string[]]>;

    /**
     * Gets the package version
     */
    version(overrides?: CallOverrides): Promise<[BigNumber]>;

    /**
     * This function is invoked when the Extension is registered with a TokenProxy
     * This function cannot be invoked directly
     */
    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    addBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    addBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onTransferExecuted(
      data: TransferDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  /**
   * Gets the extension deployer address
   */
  extensionDeployer(overrides?: CallOverrides): Promise<string>;

  /**
   * This function is used by the TokenProxy to determine what function selectors to add to the TokenProxy
   * An array of function signatures registered by the extension
   */
  externalFunctions(overrides?: CallOverrides): Promise<string[]>;

  hasRole(
    caller: PromiseOrValue<string>,
    roleId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * The ERC1820 interface label the extension will be registered as in the ERC1820 registry
   */
  interfaceLabel(overrides?: CallOverrides): Promise<string>;

  /**
   * Checks if token standard is supported by the extension
   * @param standard a valid TokenStandard (enum)
   */
  isTokenStandardSupported(
    standard: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * Gets the package hash (generated using the package name and deployer address)
   */
  packageHash(overrides?: CallOverrides): Promise<string>;

  /**
   * Gets the list of required roles required to call the extension
   */
  requiredRoles(overrides?: CallOverrides): Promise<string[]>;

  /**
   * Gets the package version
   */
  version(overrides?: CallOverrides): Promise<BigNumber>;

  /**
   * This function is invoked when the Extension is registered with a TokenProxy
   * This function cannot be invoked directly
   */
  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isBlocklisted(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  addBlocklisted(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeBlocklisted(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isBlocklistedAdmin(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  addBlocklistedAdmin(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeBlocklistedAdmin(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onTransferExecuted(
    data: TransferDataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * Gets the extension deployer address
     */
    extensionDeployer(overrides?: CallOverrides): Promise<string>;

    /**
     * This function is used by the TokenProxy to determine what function selectors to add to the TokenProxy
     * An array of function signatures registered by the extension
     */
    externalFunctions(overrides?: CallOverrides): Promise<string[]>;

    hasRole(
      caller: PromiseOrValue<string>,
      roleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * The ERC1820 interface label the extension will be registered as in the ERC1820 registry
     */
    interfaceLabel(overrides?: CallOverrides): Promise<string>;

    /**
     * Checks if token standard is supported by the extension
     * @param standard a valid TokenStandard (enum)
     */
    isTokenStandardSupported(
      standard: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * Gets the package hash (generated using the package name and deployer address)
     */
    packageHash(overrides?: CallOverrides): Promise<string>;

    /**
     * Gets the list of required roles required to call the extension
     */
    requiredRoles(overrides?: CallOverrides): Promise<string[]>;

    /**
     * Gets the package version
     */
    version(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * This function is invoked when the Extension is registered with a TokenProxy
     * This function cannot be invoked directly
     */
    initialize(overrides?: CallOverrides): Promise<void>;

    isBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    isBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    onTransferExecuted(
      data: TransferDataStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "BlocklistedAdded(address)"(
      account?: PromiseOrValue<string> | null
    ): BlocklistedAddedEventFilter;
    BlocklistedAdded(
      account?: PromiseOrValue<string> | null
    ): BlocklistedAddedEventFilter;

    "BlocklistedAdminAdded(address)"(
      account?: PromiseOrValue<string> | null
    ): BlocklistedAdminAddedEventFilter;
    BlocklistedAdminAdded(
      account?: PromiseOrValue<string> | null
    ): BlocklistedAdminAddedEventFilter;

    "BlocklistedAdminRemoved(address)"(
      account?: PromiseOrValue<string> | null
    ): BlocklistedAdminRemovedEventFilter;
    BlocklistedAdminRemoved(
      account?: PromiseOrValue<string> | null
    ): BlocklistedAdminRemovedEventFilter;

    "BlocklistedRemoved(address)"(
      account?: PromiseOrValue<string> | null
    ): BlocklistedRemovedEventFilter;
    BlocklistedRemoved(
      account?: PromiseOrValue<string> | null
    ): BlocklistedRemovedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "RoleAdded(address,bytes32)"(
      caller?: PromiseOrValue<string> | null,
      roleId?: PromiseOrValue<BytesLike> | null
    ): RoleAddedEventFilter;
    RoleAdded(
      caller?: PromiseOrValue<string> | null,
      roleId?: PromiseOrValue<BytesLike> | null
    ): RoleAddedEventFilter;

    "RoleRemoved(address,bytes32)"(
      caller?: PromiseOrValue<string> | null,
      roleId?: PromiseOrValue<BytesLike> | null
    ): RoleRemovedEventFilter;
    RoleRemoved(
      caller?: PromiseOrValue<string> | null,
      roleId?: PromiseOrValue<BytesLike> | null
    ): RoleRemovedEventFilter;
  };

  estimateGas: {
    /**
     * Gets the extension deployer address
     */
    extensionDeployer(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * This function is used by the TokenProxy to determine what function selectors to add to the TokenProxy
     * An array of function signatures registered by the extension
     */
    externalFunctions(overrides?: CallOverrides): Promise<BigNumber>;

    hasRole(
      caller: PromiseOrValue<string>,
      roleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * The ERC1820 interface label the extension will be registered as in the ERC1820 registry
     */
    interfaceLabel(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Checks if token standard is supported by the extension
     * @param standard a valid TokenStandard (enum)
     */
    isTokenStandardSupported(
      standard: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Gets the package hash (generated using the package name and deployer address)
     */
    packageHash(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Gets the list of required roles required to call the extension
     */
    requiredRoles(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Gets the package version
     */
    version(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * This function is invoked when the Extension is registered with a TokenProxy
     * This function cannot be invoked directly
     */
    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onTransferExecuted(
      data: TransferDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Gets the extension deployer address
     */
    extensionDeployer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * This function is used by the TokenProxy to determine what function selectors to add to the TokenProxy
     * An array of function signatures registered by the extension
     */
    externalFunctions(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hasRole(
      caller: PromiseOrValue<string>,
      roleId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * The ERC1820 interface label the extension will be registered as in the ERC1820 registry
     */
    interfaceLabel(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Checks if token standard is supported by the extension
     * @param standard a valid TokenStandard (enum)
     */
    isTokenStandardSupported(
      standard: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Gets the package hash (generated using the package name and deployer address)
     */
    packageHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Gets the list of required roles required to call the extension
     */
    requiredRoles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Gets the package version
     */
    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * This function is invoked when the Extension is registered with a TokenProxy
     * This function cannot be invoked directly
     */
    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeBlocklisted(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeBlocklistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onTransferExecuted(
      data: TransferDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
