/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface IAllowlistedAdminRoleInterface extends utils.Interface {
  functions: {
    "isAllowlistedAdmin(address)": FunctionFragment;
    "addAllowlistedAdmin(address)": FunctionFragment;
    "removeAllowlistedAdmin(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "isAllowlistedAdmin"
      | "addAllowlistedAdmin"
      | "removeAllowlistedAdmin"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isAllowlistedAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addAllowlistedAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAllowlistedAdmin",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "isAllowlistedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAllowlistedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAllowlistedAdmin",
    data: BytesLike
  ): Result;

  events: {
    "AllowlistedAdminAdded(address)": EventFragment;
    "AllowlistedAdminRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AllowlistedAdminAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AllowlistedAdminRemoved"): EventFragment;
}

export interface AllowlistedAdminAddedEventObject {
  account: string;
}
export type AllowlistedAdminAddedEvent = TypedEvent<
  [string],
  AllowlistedAdminAddedEventObject
>;

export type AllowlistedAdminAddedEventFilter =
  TypedEventFilter<AllowlistedAdminAddedEvent>;

export interface AllowlistedAdminRemovedEventObject {
  account: string;
}
export type AllowlistedAdminRemovedEvent = TypedEvent<
  [string],
  AllowlistedAdminRemovedEventObject
>;

export type AllowlistedAdminRemovedEventFilter =
  TypedEventFilter<AllowlistedAdminRemovedEvent>;

export interface IAllowlistedAdminRole extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAllowlistedAdminRoleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    addAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  isAllowlistedAdmin(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  addAllowlistedAdmin(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeAllowlistedAdmin(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    isAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AllowlistedAdminAdded(address)"(
      account?: PromiseOrValue<string> | null
    ): AllowlistedAdminAddedEventFilter;
    AllowlistedAdminAdded(
      account?: PromiseOrValue<string> | null
    ): AllowlistedAdminAddedEventFilter;

    "AllowlistedAdminRemoved(address)"(
      account?: PromiseOrValue<string> | null
    ): AllowlistedAdminRemovedEventFilter;
    AllowlistedAdminRemoved(
      account?: PromiseOrValue<string> | null
    ): AllowlistedAdminRemovedEventFilter;
  };

  estimateGas: {
    isAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeAllowlistedAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
